/*
 *  HarmonicOscillator_gvf.h
 *
 *  GSL C prototype file for the functions defined in HarmonicOscillator_gvf.c
 *
 *  This file was generated by the program VFGEN, version: 2.6.0.dev1
 *  Generated on 19-Oct-2021 at 14:43
 */

int HarmonicOscillator_vf(double, const double [], double [], void *);
int HarmonicOscillator_jac(double, const double [], double *, double *, void *);
int HarmonicOscillator_jacp(double, const double [], double *, void *);
double HarmonicOscillator_flux(double, const double [], void *);
